version: 2.1

jobs:
  build:
    docker:
      - image: fpco/stack-build:lts-13.19
    steps:
      - checkout
      - restore_cache:
          name: Restore Cached Dependencies
          keys:
            - TypedFlow-v1-{{ checksum "stack.yaml" }}-{{ checksum "package.yaml" }}
            - TypedFlow-v1-{{ checksum "stack.yaml" }}
      - run:
          name: Resolve/Update Dependencies
          command: stack setup
      - run:
          name: Run tests
          command: stack test
      # - run:
      #     name: Install executable
      #     command: stack install
      - save_cache:
          name: Cache Dependencies
          key: TypedFlow-v1-{{ checksum "stack.yaml" }}-{{ checksum "package.yaml" }}
          paths:
            - "/root/.stack"
            - ".stack-work"
      # - store_artifacts:
      #     # Upload test summary for display in Artifacts: https://circleci.com/docs/2.0/artifacts/ 
      #     path: ~/.local/bin/circleci-demo-haskell-exe
      #     destination: circleci-demo-haskell-exe
